trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  serviceConnection: 'azure-free-trial-sc'

steps:
- checkout: self

- script: |
    wget -q https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip
    unzip terraform_1.8.5_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    terraform version
  displayName: Install Terraform

- task: AzureCLI@2
  displayName: Terraform Init
  inputs:
    azureSubscription: $(serviceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: terraform init

- task: AzureCLI@2
  displayName: Terraform Validate
  inputs:
    azureSubscription: $(serviceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: terraform validate

- task: AzureCLI@2
  displayName: Terraform Plan
  inputs:
    azureSubscription: $(serviceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: terraform plan

- task: AzureCLI@2
  displayName: Terraform Apply
  inputs:
    azureSubscription: $(serviceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: terraform apply -auto-approve
